#!/usr/bin/env php
<?php
/**
 * build.php
 * @author Revin Roman http://phptime.ru
 */

foreach ([
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../../vendor/autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php',
         ] as $file) {
    if (file_exists($file)) {
        define('COOKYII_BUILD_COMPOSER_INSTALL', realpath($file));
        break;
    }
}

if (!defined('COOKYII_BUILD_COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require_once COOKYII_BUILD_COMPOSER_INSTALL;

(new \cookyii\build\applications\BuildApplication())
    ->run();